# Generated by Django 3.1 on 2020-08-13 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=50)),
                ('subrubro', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=70)),
                ('ciudad', models.CharField(max_length=50)),
                ('cobertura', models.CharField(max_length=10)),
                ('contacto', models.CharField(max_length=100)),
                ('envio', models.CharField(max_length=100)),
                ('horarios', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
