# Generated by Django 3.1 on 2020-08-27 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import emprens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('rubro', models.CharField(max_length=50)),
                ('subrubro', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=emprens.models.upload_image_path)),
                ('direccion', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=70)),
                ('ciudad', models.CharField(max_length=50)),
                ('cobertura', models.CharField(max_length=10)),
                ('contacto', models.CharField(max_length=100)),
                ('envio', models.CharField(max_length=100)),
                ('horarios', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empren', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=emprens.models.upload_image_path)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=emprens.models.upload_image_path)),
                ('precio', models.IntegerField(default=0)),
                ('stock', models.BooleanField(default=True)),
                ('emprendimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='emprens.emprendimiento')),
            ],
        ),
    ]
