# Generated by Django 3.1 on 2020-08-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='emprens/'),
        ),
    ]
