# Generated by Django 3.1 on 2020-08-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='emprendimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emprens.emprendimiento'),
        ),
    ]
