# Generated by Django 3.1 on 2020-08-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprens', '0002_auto_20200827_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprendimiento',
            old_name='contacto',
            new_name='cont_insta',
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='cont_mail',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='cont_whatsapp',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='inmediato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='barrio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='cobertura',
            field=models.CharField(max_length=100),
        ),
    ]
