# Generated by Django 3.1 on 2020-08-13 20:48

from django.db import migrations, models
import emprens.models


class Migration(migrations.Migration):

    dependencies = [
        ('emprens', '0002_emprendimiento_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=emprens.models.upload_image_path),
        ),
    ]
