# Generated by Django 3.1 on 2020-08-13 21:10

from django.db import migrations, models
import emprens.models


class Migration(migrations.Migration):

    dependencies = [
        ('emprens', '0003_auto_20200813_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=emprens.models.upload_image_path),
        ),
    ]
