# Generated by Django 3.1 on 2020-08-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprens', '0004_auto_20200813_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
