# Generated by Django 3.1 on 2020-08-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprens', '0006_emprendimiento_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
