# Generated by Django 3.1 on 2020-08-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprens', '0008_emprendimiento_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
